# coding:utf-8
"""
Given two strings s and t which consist of only lowercase letters.

String t is generated by random shuffling string s and then add one more letter at a random position.

Find the letter that was added in t.

Example:

Input:
s = "abcd"
t = "abcde"

Output:
e

Explanation:
'e' is the letter that was added.
"""


class Solution(object):
    def findTheDifference(self, s, t):
        """
        :type s: str
        :type t: str
        :rtype: str
        """
        s_dict = {}
        t_dict = {}
        for v1 in s:
            if v1 not in s_dict:
                s_dict[v1] = 1
            else:
                s_dict[v1] += 1
        for v2 in t:
            if v2 not in t_dict:
                t_dict[v2] = 1
            else:
                t_dict[v2] += 1
        for v in t_dict:
            if not s_dict.get(v):
                return v
            if s_dict[v] != t_dict[v]:
                return v
